"""Add room assignment for readers

Revision ID: 882307784a69
Revises: 89cb3e63c04d
Create Date: 2025-07-16 18:16:58.675411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882307784a69'
down_revision = '89cb3e63c04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add the column as nullable
    with op.batch_alter_table('reader_tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_number', sa.Integer(), nullable=True))
    
    # Set a default value for existing rows
    op.execute('UPDATE reader_tournament SET room_number = 1 WHERE room_number IS NULL')
    
    # Then alter the column to be NOT NULL
    with op.batch_alter_table('reader_tournament', schema=None) as batch_op:
        batch_op.alter_column('room_number', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reader_tournament', schema=None) as batch_op:
        batch_op.drop_column('room_number')

    # ### end Alembic commands ###
