"""Initial migration

Revision ID: 89cb3e63c04d
Revises: 
Create Date: 2025-07-16 17:44:19.713494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '89cb3e63c04d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('reader_room_assignment')
    op.drop_table('bonus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('leadin', sa.TEXT(), nullable=False),
    sa.Column('parts', sqlite.JSON(), nullable=False),
    sa.Column('answers', sqlite.JSON(), nullable=False),
    sa.Column('question_number', sa.INTEGER(), nullable=False),
    sa.Column('round', sa.INTEGER(), nullable=False),
    sa.Column('stage', sa.VARCHAR(length=50), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_bonus_question'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], name='fk_bonus_tournament'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reader_room_assignment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reader_id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('room_number', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['reader_id'], ['reader.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'reader_id', name='_tournament_reader_uc'),
    sa.UniqueConstraint('tournament_id', 'room_number', name='_tournament_room_uc')
    )
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
